use_frameworks!

target 'Example' do
  pod 'Mindbox', '2.11.2'
end

target 'MindboxNotificationServiceExtension' do
   pod 'MindboxNotifications', '2.11.2'
end

target 'MindboxNotificationContentExtension' do
   pod 'MindboxNotifications', '2.11.2'
end
