use_frameworks!

target 'Example' do
  pod 'Mindbox', '2.10.1'
end

target 'MindboxNotificationServiceExtension' do
   pod 'MindboxNotifications', '2.10.1'
end

target 'MindboxNotificationContentExtension' do
   pod 'MindboxNotifications', '2.10.1'
end
