# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'ExampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for ExampleApp
  pod 'Mindbox', '2.8.5'

end


target 'MindboxNotificationServiceExtension' do

  pod 'MindboxNotifications', '2.8.5'

end


target 'MindboxNotificationContentExtension' do

  pod 'MindboxNotifications', '2.8.5'

end