name: PushOk (Develop PR Merge)

on:
  pull_request:
    branches:
      - develop
      - main
      - feature/*
    types:
      - closed

jobs:
  call-reusable:
    if: ${{ github.event.pull_request.merged == true }}
    uses: ./.github/workflows/distribute-reusable.yml
    secrets: inherit 
