name: SwiftLint & UnitTests

on:
  push:
    branches:
      - develop
      - poziev/test-var
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      
jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:latest
    steps:
    - uses: actions/checkout@v6
    - run: echo ${{secrets.LOOP_NOTIFICATION_WEBHOOK_URL}}
