name: SwiftLint & UnitTests

on:
  push:
    branches:
      - develop
      - mission/*
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      
permissions:
  contents: read

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:latest
    steps:
    - uses: actions/checkout@v6
    - run: swiftlint --config .swiftlint.yml --reporter github-actions-logging --strict

  build:
    runs-on: macos-26
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v6
    - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
      with:
        xcode-version: latest-stable

    - name: Update bundler
      run: gem install bundler
    - name: Install bundler dependencies
      run: bundle install
    - name: Install yeetd
      run: |
          wget https://github.com/biscuitehh/yeetd/releases/download/1.0/yeetd-normal.pkg
          sudo installer -pkg yeetd-normal.pkg -target /
          yeetd &
    - name: Run unit tests
      run: bundle exec fastlane unitTestLane
