name: SwiftLint & UnitTests

on:
  push:
    branches:
      - develop
      - mission/*
      - '**'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      
jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:latest   # или :latest
    steps:
      - uses: actions/checkout@v4
      - run: swiftlint --config .swiftlint.yml --reporter github-actions-logging

  build:
    runs-on: macos-15
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Update bundler
      run: gem install bundler
    - name: Install bundler dependencies
      run: bundle install
    - name: Install yeetd
      run: |
          wget https://github.com/biscuitehh/yeetd/releases/download/1.0/yeetd-normal.pkg
          sudo installer -pkg yeetd-normal.pkg -target /
          yeetd &
    - name: Run unit tests
      run: bundle exec fastlane unitTestLane
