name: SDK publish

on:
  pull_request:
    types: [closed]
    branches:
      - 'test-logger-release/*.*.*'
jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4 
      - name: Update bundler
        run: gem install bundler
      - name: Install bundler dependencies
        run: bundle install
      - name: Deploy to Cocoapods
        run: |
          set -eo pipefail
          pod lib lint --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TOKEN }}
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C06RXV161RA'
          payload: |
            {
              "text": "iOS - MindboxLogger release",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "🚀 MindboxLogger tested."
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_MOBILE_NOTIFIER_TOKEN }}
